### ISSUE TITLE
Framework settings restore & admin notice not working.

### ISSUE THREAD

**Issue by wpbean** [wpsf/wpsf#1]
When I try to restore the framework settings, an error comes out.

I tried and managed to fix the error but the admin notice on saving and restoring the options is not showing.

Can you please fix this issue.

`Fatal error: Uncaught Error: Call to undefined method WPSFramework_Settings::add_settings_error() in /app/public/wp-content/plugins/wpb-testimonial/admin/classes/settings.php:353 Stack trace: #0 /app/public/wp-includes/class-wp-hook.php(288): WPSFramework_Settings->validate_save(Array) #1 /app/public/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array) #2 /app/public/wp-includes/formatting.php(4314): apply_filters('sanitize_option...', Array, '_wpsf_new_optio...', Array) #3 /app/public/wp-includes/option.php(297): sanitize_option('_wpsf_new_optio...', Array) #4 /app/public/wp-admin/options.php(274): update_option('_wpsf_new_optio...', Array) #5 {main} thrown in /app/public/wp-content/plugins/wpb-testimonial/admin/classes/settings.php on line 353`

Thanks

**Comment by varunsridharan** [comment]
Hi @wpbean 

We are no longer working in this (WPSF Framework) And we shifted to (WPOnion) https://github.com/wponion/dev
which is also a wordpress options framework.

for docs you can look @ http://wponion.gitbook.io/docs/

Its still in Beta.
